import assert from 'node:assert/strict';
import { realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import test from 'node:test';
import pg from 'pg';
import { postgresDatabase } from '../enrollment/store';
import { createTelemetryServer } from './server';
import { commonTests, migrations, realm, setup } from './test-support';
const socket=process.env.ARBI_ENROLLMENT_TEST_SOCKET;
test('native PostgreSQL telemetry: retention, bounded HTTP queries, atomic replay and independent connections',{skip:!socket,timeout:45000},async t=>{
  const root=realpathSync(socket!);assert.ok(root.startsWith(`${realpathSync(process.platform==='darwin'?'/private/tmp':tmpdir())}/arbi-enrollment-pg-`));
  const admin=new pg.Pool({host:root,user:'arbi_test',port:54321,database:'postgres',max:1});
  await admin.query('CREATE DATABASE arbi_telemetry_test');await admin.end();
  const config={host:root,user:'arbi_test',port:54321,database:'arbi_telemetry_test',max:4};
  const pool=new pg.Pool(config),other=new pg.Pool({...config,max:1});
  t.after(async()=>{await other.end();await pool.end();});
  t.diagnostic(`Native PostgreSQL ${(await pool.query('SHOW server_version')).rows[0].server_version}`);
  const db=postgresDatabase(pool);await migrations(pool);await commonTests(t,db,pool);
  await t.test('concurrent duplicates aggregate once; replay/rows and outbox roll back together',async()=>{
    const f=await setup(db,pool);await f.ingest(f.snapshot());
    const independent=createTelemetryServer({db:postgresDatabase(other),realm,identity:f.identity.adapter,resolveSite:f.identity.resolveResource,
      currentAuthority:f.currentAuthority,browserOrigins:['https://synthetic.test']});
    const m=f.sample(1),results:any[]=await Promise.all([f.ingest(m),independent.store.device(f.siteId,f.signed(m))]);
    assert.deepEqual(new Set(results.map(r=>r.decision)),new Set(['recorded','duplicate']));
    assert.equal((await pool.query("SELECT record->>'count' AS count FROM arbi_telemetry_history WHERE site_id=$1 AND tier='hour'",[f.siteId])).rows[0].count,'1');
    const cursor=(await pool.query('SELECT cursor FROM arbi_realtime_sites WHERE site_id=$1',[f.siteId])).rows[0].cursor;
    await pool.query('ALTER TABLE arbi_realtime_events ADD CONSTRAINT telemetry_injected_failure CHECK(false) NOT VALID');
    await assert.rejects(f.ingest(f.sample(2)),{code:'UNAVAILABLE'});
    assert.equal((await pool.query('SELECT cursor FROM arbi_realtime_sites WHERE site_id=$1',[f.siteId])).rows[0].cursor,cursor);
    assert.equal((await pool.query("SELECT record->>'count' AS count FROM arbi_telemetry_history WHERE site_id=$1 AND tier='hour'",[f.siteId])).rows[0].count,'1');
    await pool.query('ALTER TABLE arbi_realtime_events DROP CONSTRAINT telemetry_injected_failure');
    await independent.store.device(f.siteId,f.signed(f.sample(2)));
    assert.equal((await pool.query('SELECT kind FROM arbi_realtime_events WHERE site_id=$1 ORDER BY cursor DESC LIMIT 1',[f.siteId])).rows[0].kind,'state');
    const current:any=await independent.store.read(await f.context('state.read'),'current',{});assert.equal(current.states.find((s:any)=>s.message.kind==='telemetry').message.sequence,'2');
    const lock=await pool.connect();await lock.query('BEGIN');await lock.query('SELECT state FROM arbi_device_registry WHERE site_id=$1 FOR UPDATE',[f.siteId]);
    const started=Date.now();await assert.rejects(independent.store.read(await f.context('state.read'),'current',{}),{code:'UNAVAILABLE'});
    assert.ok(Date.now()-started<3000);await lock.query('ROLLBACK');lock.release();
  });
  await t.test('HTTP current authority, origin and proof checks plus strict filtered queries use real migrated SQL',async()=>{
    const f=await setup(db,pool);await f.ingest(f.snapshot());await f.ingest(f.sample(1));
    const request=(action:string,query='',token=f.human.token)=>new Request(`https://synthetic.test/api/sites/${f.siteId}/telemetry/${action}${query}`,{headers:{authorization:`Bearer ${token}`}});
    const handle=(action:string,query='')=>f.server.handle(request(action,query),{siteId:f.siteId,action});
    const current=await handle('current');assert.equal(current.status,200);assert.equal(current.headers.get('cache-control'),'private, no-store');
    assert.equal((await handle('history',`?tier=raw&fromMs=${Date.now()-60000}&toMs=${Date.now()+1000}&limit=1`)).status,200);
    assert.equal((await handle('inventory','?assemblyId=assembly-a&limit=1')).status,200);
    assert.equal((await handle('current','?limit=1&limit=2')).status,400);
    assert.equal((await handle('history','?tier=raw&fromMs=0&toMs=1&limit=101')).status,400);
    const signedRequest=(body:unknown,headers:Record<string,string>={})=>new Request('https://synthetic.test/device',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
    const signed=f.signed(f.sample(2));
    assert.equal((await f.server.handle(signedRequest(signed,{origin:'https://synthetic.test'}),{siteId:f.siteId,action:'device'})).status,403);
    assert.equal((await f.server.handle(signedRequest({...signed,signature:'a'.repeat(86)}),{siteId:f.siteId,action:'device'})).status,403);
    assert.equal((await f.server.handle(signedRequest(signed),{siteId:f.siteId,action:'device'})).status,200);
    assert.equal((await f.server.handle(signedRequest({padding:'x'.repeat(60_001)}),{siteId:f.siteId,action:'device'})).status,400);
    const viewer={kind:'human' as const,id:'viewer'};
    const issued=await f.createHuman('viewer','state.read');
    f.identity.putPrincipal({actor:viewer,accountId:f.registry.accountId,member:true,sites:{[f.siteId]:{roles:['viewer'],serviceScopes:[],active:true,revision:'viewer-1'}}});
    assert.equal((await f.server.handle(request('current','',issued.token),{siteId:f.siteId,action:'current'})).status,200);
    assert.equal((await f.server.handle(request('inventory','',issued.token),{siteId:f.siteId,action:'inventory'})).status,403);
    assert.equal((await f.server.handle(request('history',`?tier=trace&fromMs=${Date.now()-60000}&toMs=${Date.now()+1000}&limit=1`,issued.token),{siteId:f.siteId,action:'history'})).status,403);
    f.identity.putSite(f.siteId,'different-account');assert.equal((await handle('current')).status,403);
    f.identity.putSite(f.siteId,f.registry.accountId);
    f.identity.revoke(f.human.sessionId);assert.equal((await handle('current')).status,401);
  });
});
