import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { test } from "node:test";
import pg from "pg";
import { postgresDatabase } from "../enrollment/store";
import { provisionDashboardTest } from "./provision-test";
import { createDashboardTestProvider } from "./test-provider";
const socket = process.env.ARBI_ENROLLMENT_TEST_SOCKET;
test("native PostgreSQL dashboard: independent instances share current directory, sessions, revocation and durable audit", { skip: !socket, timeout: 30000 }, async t => {
  const root = realpathSync(socket!); assert.ok(root.startsWith(`${realpathSync(process.platform === "darwin" ? "/private/tmp" : tmpdir())}/arbi-enrollment-pg-`));
  const admin = new pg.Pool({ host: root, user: "arbi_test", port: 54321, database: "postgres", max: 1 });
  await admin.query("CREATE DATABASE arbi_dashboard_test"); await admin.end();
  const pool = new pg.Pool({ host: root, user: "arbi_test", port: 54321, database: "arbi_dashboard_test", max: 4 });
  const other = new pg.Pool({ host: root, user: "arbi_test", port: 54321, database: "arbi_dashboard_test", max: 2 });
  t.after(async () => { await pool.end(); await other.end(); });
  const realm = { environment: "test" as const, namespaceId: "synthetic-dashboard" };
  await provisionDashboardTest(postgresDatabase(pool), realm);
  const config = { realm, verificationKey: randomBytes(32), accessCode: "s".repeat(48), browserOrigins: ["http://localhost:3000"] };
  const a = createDashboardTestProvider({ ...config, db: postgresDatabase(pool) });
  const b = createDashboardTestProvider({ ...config, db: postgresDatabase(other) });
  const token = (await a.login(config.accessCode))!;
  const request = new Request("http://localhost:3000/", { headers: { authorization: `Bearer ${token}` } });
  const response = await b.server.handle(request, "synthetic-site"); assert.equal(response.status, 200);
  const context = await response.json(); assert.equal(context.identity.actorId, "synthetic-engineer");
  const before = Number((await pool.query("SELECT COUNT(*) FROM arbi_audit_history")).rows[0].count);
  await pool.query("UPDATE arbi_dashboard_memberships SET active=false,revision='membership-2' WHERE actor_id='synthetic-engineer'");
  assert.equal((await b.server.handle(request, "synthetic-site")).status, 403);
  await pool.query("UPDATE arbi_dashboard_memberships SET active=true WHERE actor_id='synthetic-engineer'");
  await a.revoke(token); assert.equal((await b.server.handle(request, "synthetic-site")).status, 401);
  assert.ok(Number((await pool.query("SELECT COUNT(*) FROM arbi_audit_history")).rows[0].count) > before);
});
